---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - es.upv.grycap.es.upv.grycap
  resources:
  - korgijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.upv.grycap.es.upv.grycap
  resources:
  - korgijobs/finalizers
  verbs:
  - update
- apiGroups:
  - es.upv.grycap.es.upv.grycap
  resources:
  - korgijobs/status
  verbs:
  - get
  - patch
  - update
