# Dockerfile to create a container for training Tensorflow Models
#
# 20220401 - Estibaliz Parcero

# https://hub.docker.com/r/tensorflow/tensorflow
FROM tensorflow/tensorflow:2.6.0-gpu

RUN python3 -m pip install --upgrade pip

RUN pip install matplotlib