apiVersion: es.upv.grycap.es.upv.grycap/v1
kind: KorgiJob
metadata:
  name: prueba01
  namespace: kubernetes-admin-mig-1g
spec:
  image: esparig/testing-tf-models:latest
  command: ["/bin/bash","-c","cd /usr/local/lib/python3.6/dist-packages/official && python3 vision/image_classification/mnist_main.py --model_dir=$MODEL_DIR --data_dir=$DATA_DIR --train_epochs=40 --download"]
