name: Docker Image CI TF and Model Garden
on:
  push:
    paths:
    - 'dockerfiles/tf-models/**'

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: esparig/tf-models
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: dockerfiles/tf-models/Dockerfile
        context: dockerfiles/tf-models/